# =============================================================================
# OurChat Secrets for Oracle Cloud
# =============================================================================
# This file is encrypted with SOPS + age. DO NOT commit unencrypted.
# To edit: sops apps/oracle/secrets/ourchat-secrets.yaml
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
    name: ourchat-secrets
    namespace: ourchat
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:kscPlwQaYIzBE3qVxOE0UaQYIMe0M1JnqA7TfMCAYeq4ixsmhxJKJaT1xtvarJDnfHmpZo8/3kK8viiIKg==,iv:DX6yU0aYNcvQa0/SQi5ZuTOFx0j2GkThMGj4jOgFNlU=,tag:KkUZr9G41lvJ3uK6r0XzcQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:LsiZpSP1F/LPwoZHNCF1IK1cicdqv/Qp8HdXUdy0s/2BgpYXL5iURlKsofuiUidTx76VaD8/cNpq7HYnoQ8+ug==,iv:JNktYOSlKPG25qbBdH1vt1hy7v4aC+xl6NE7FgMg9a4=,tag:4jLd3ulAi02asaBCBPb1XQ==,type:str]
    REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:bmuoz1DBPNg5S7HnHDXL760iQEQOc4QmmxyJRtDyvteqw4VgsZOILOgTp4hIOhNusG62MUWCvibhHpYKyHhmUg==,iv:m82UEz8ediB30/HNYfKRmrYhCfk+75MZqjOpsEIO+kU=,tag:dQbFFCQmgQS1SMr50IyfJw==,type:str]
    INVITE_SECRET: ENC[AES256_GCM,data:QypWvJOrvXEd/8Jh5K0viF2sNUwSZxT+sOpxKCsAmlmv4T1o+wiVeR0mYknOXtvoPwDSHj7TkF7+wG+FnXc0+A==,iv:N+WavQDzgSMRGU78W6AxBgmAedTjkXgg4vkPKt94Osk=,tag:ggYUKCXiF2Alv85+o1UNzQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:mmO13oJQrzoKe1VEFtoIFSWMitQMtU/J,iv:guVGNuyo9JkbCeIQ5DOZOUqiiCHRCr4PcW+r3hll3eI=,tag:DBz/5PvQ7/0TJq0JIlJ3oA==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:oyIb30ysxBZ41hH/2q+T+Q35rHOw/8d6KP670wCFUDqBbChCo36ky9mtWIm19A+By5kaXqFR4ha3Gy1kg83bw4EnBe+r+RdGa/Pyw+BfDAAT0hTGw/Oqo7/q,iv:PuQzQrJxXFBN1UpOiCCmgT3n4m3nEEBVQEcEfAH3qyw=,tag:hXJ3LCoWNNc61R1QVujoKw==,type:str]
sops:
    age:
        - recipient: age16a8nqctg868rxvpafsvremquhnecp0d9xh5ws98asqh7ayy5a5qsq6thv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpT2N0SGl0djJJejN1Ulkw
            WWZXVjNvcHgyM00zKzh6THhhMmR3Z0ExVjNVCmxuZWMvTmhYalE1RFJMRTBmRDFz
            WUJoWGVDVUd6V0VzN04yUU1EZ0hQQ2MKLS0tIGZvakd1ejgxd0pubWpsMlpOT3NX
            Um92RmdlNWtqYmNIMkV4WXlQaTVOODQKoDNdWvcrXvFZh5lfO2ZCmdCKpE0M09yl
            luscCUwpcj+SIA9QJqUFc42ieG3j/uk1+Z3QW2xykngcH4pc98A5DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T03:46:41Z"
    mac: ENC[AES256_GCM,data:2crivdNUo3KRIDJJHWe/sWlhwlaI1afZ08UvYvIqoTykkGsECcM4CueatX0Vx7vmUgvEZ+bTYfuhgX8q+NMIufUh0hvoXUrXQRDGzYkq35u7agvRNqCfvPaj0tB8vZ0ohxdbXUT2lJmpvJ7FicsKP/5Mlu8rblAtbTcai/htFkA=,iv:gxlrtcrz8kpsv3WZlQ8IGUdU+0wnASywZIndexfSCow=,tag:Dn8NIhqP+M29XrFZX6q/SA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
