apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ourchat-frontend
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: generic-service
      version: ">=0.1.0"
      sourceRef:
        kind: HelmRepository
        name: platform-charts
  targetNamespace: ourchat
  values:
    replicaCount: 1
    image:
      # Image policy markers for Flux image automation
      repository: k3d-registry.localhost:5000/ourchat/frontend # {"$imagepolicy": "flux-system:ourchat-frontend:name"}
      tag: f6ab5f7-1768025762 # {"$imagepolicy": "flux-system:ourchat-frontend:tag"}
      pullPolicy: Always
    service:
      enabled: true
      port: 3000
    healthcheck:
      enabled: true
      path: /
      port: 3000
      initialDelaySeconds: 5
      periodSeconds: 10
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
    env:
      - name: NEXT_PUBLIC_GRAPHQL_HTTP_URL
        value: "http://api.ourchat.localhost/graphql"
      - name: NEXT_PUBLIC_GRAPHQL_WS_URL
        value: "ws://api.ourchat.localhost/graphql"
