---
# Istio system namespace
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-injection: disabled
---
# Istio ingress namespace
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  labels:
    istio-injection: enabled
---
# Istio Helm repository (in istio-system namespace for proper access)
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 30m
  url: https://istio-release.storage.googleapis.com/charts
---
# Istio Base (CRDs)
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: base
      version: ">=1.20.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
---
# Istiod (Control Plane)
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 30m
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: istiod
      version: ">=1.20.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  values:
    pilot:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
---
# Istio Gateway (Ingress)
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-ingress
spec:
  interval: 30m
  dependsOn:
    - name: istiod
      namespace: istio-system
  chart:
    spec:
      chart: gateway
      version: ">=1.20.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  values:
    service:
      type: LoadBalancer
      ports:
        - name: http
          port: 80
          targetPort: 80
        - name: https
          port: 443
          targetPort: 443
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
