---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: ">=7.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
  targetNamespace: observability
  values:
    # Admin credentials (override in production)
    adminUser: admin
    adminPassword: admin123

    # Persistence disabled for local dev
    persistence:
      enabled: false

    # Resources
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    # Datasources
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-kube-prometheus-prometheus.observability.svc.cluster.local:9090
            access: proxy
            isDefault: true
          - name: Loki
            type: loki
            url: http://loki.observability.svc.cluster.local:3100
            access: proxy

    # Service configuration
    service:
      type: ClusterIP
      port: 80

    # Enable service monitor for Prometheus scraping
    serviceMonitor:
      enabled: true

    # Sidecar for dashboards
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
