---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: ">=5.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
  targetNamespace: observability
  values:
    # Single binary deployment mode (suitable for local dev)
    deploymentMode: SingleBinary

    loki:
      # Authentication disabled for local dev
      auth_enabled: false

      # Common config
      commonConfig:
        replication_factor: 1

      # Storage config - filesystem for local dev
      storage:
        type: filesystem

      # Schema config
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h

    # Single binary configuration
    singleBinary:
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 512Mi
      persistence:
        enabled: true
        size: 5Gi

    # Disable components not needed for single binary mode
    gateway:
      enabled: false
    read:
      replicas: 0
    write:
      replicas: 0
    backend:
      replicas: 0

    # Disable caching for local dev
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false

    # Service monitor
    serviceMonitor:
      enabled: true

    # Test disabled
    test:
      enabled: false
