---
# Infrastructure controllers (cert-manager, Istio)
# Must be deployed first before other infrastructure
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-controllers
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/controllers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cert-manager
      namespace: flux-system
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: istio-base
      namespace: istio-system
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: istiod
      namespace: istio-system
---
# Infrastructure resources (observability, ingress, database)
# Depends on controllers being ready
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-controllers
  interval: 10m
  path: ./infrastructure/local
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
